version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: vv
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DATABASE_URL: postgres://root:root@db:5432/vv
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"