version: '3'

services:
  vroomvroom:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/static

  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_db:
    driver: local