# Generated by Django 4.2.8 on 2024-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_verified_drive_userprofile_verified_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_to_email',
            field=models.BooleanField(default=True),
        ),
    ]
